language: node_js
node_js:
  - "10"
os:
  - linux
dist: bionic
cache:
  directories:
    - "node_modules"

services:
  - docker

env:
  - YARN_GPG=no

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+/

before_install:
  - npm i -g yarn
  - if [ "$TRAVIS_BRANCH" = "master" ]; then export IMAGE_VERSION="latest"; else export IMAGE_VERSION="$TRAVIS_BRANCH"; fi
  - yarn
  - npm run build
  - yarn install --production
script:
  - docker build -t zfeng/blog:"$IMAGE_VERSION" .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push zfeng/blog:"$IMAGE_VERSION"
