version: "2"
services:
  mongo:
    image: mongo:3.6.15
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - /var/docker/volumes/mongo:/data/db
  website:
    image: zfeng/zf.ink
    restart: always
    environment:
      MAILER_PASS: Passw0rd
      MONGO: mongo
      MAILER_USER: test@test.com
    links:
      - mongo
    depends_on:
      - mongo
  nginx:
    image: nginx:1.17.6
    restart: always
    volumes:
      - /var/docker/volumes/nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_HOST=zf.ink
      - NGINX_PORT=80
    depends_on:
      - website
    links:
      - website
  redis:
    image: library/redis:6.0.1
    restart: always
    ports:
      - "6379"
